adv: gakhalh.adventure.c
	gcc -std=c89 -o gakhalh.adventure gakhalh.adventure.c -lpthread
rooms: gakhalh.buildrooms.c
	gcc -std=c89 -o gakhalh.buildrooms gakhalh.buildrooms.c
clean:
	rm -rf *.o gakhalh.adventure gakhalh.buildrooms gakhalh.rooms.1* gakhalh.rooms.2* gakhalh.rooms.3* gakhalh.rooms.4* gakhalh.rooms.5* gakhalh.rooms.6* gakhalh.rooms.7* gakhalh.rooms.8* gakhalh.rooms.9* currentTime.txt
