adv: gakhalh.adventure.c
	gcc -std=c89 -o gakhalh.adventure gakhalh.adventure.c
rooms: gakhalh.buildrooms.c
	gcc -std=c89 -o gakhalh.buildrooms gakhalh.buildrooms.c
clean:
	rm -f *.o gakhalh.adventure gakhalh.buildrooms
