#!/bin/bash
# Harinder
# 1/15/20
# cs344 hw1

# dims() will print out the dimensions of the matrix (row col)
# $ ./matrix dims [MATRIX]
dims () {
	# If user provided name of matrix file check if it exists, otherwise read from stdin
	if [[ -z $1 ]]; then
		FILE=${1:-/dev/stdin}
	elif [[ -e "$1" ]]; then
		FILE=$1
	elif [[ !(-e "$1") ]]; then
		echo "$1 does not exist!" 1>&2
		exit 1
	fi

	# Count the number of rows an columns
	row=0
	while read line; do
		col=0
		for i in $line; do
			(( col++ ))
		done
		(( row++ ))
	done < $FILE

	# Echo rows and columns to stdin
	echo "$row $col"
	return 0
}

add () {
	# Check if both matrices exist
	if [[ -e "$1" && -e "$2" ]]; then
		FILE1=$1
		FILE2=$2
	elif [[ !(-e "$1") ]]; then
		echo "$1 does not exist!" 1>&2
		exit 1
	elif [[ !(-e "$2") ]]; then
		echo "$2 does not exist!" 1>&2
		exit 1
	fi

	# Check if the dimensions of both matrices are the same
	if [[ $(dims $FILE2) == $(dims $FILE1) ]]; then
		# Use 2D arrays (dictionary) to perform calculations
		declare -A matrixA
		declare -A matrixB

		# Build first array
		row=0
		while read line; do
			col=0
			for i in $line; do
				matrixA[$row,$col]=$i
				(( col++ ))
			done
			(( row++ ))
		done < "$FILE1"

		# Build second array
		row=0
		while read line; do
			col=0
			for i in $line; do
				matrixB[$row,$col]=$i
				(( col++ ))
			done
			(( row++ ))
		done < "$FILE2"

		# Print out the sum of both matrices
		for (( i = 0; i < $row; i++ )); do
			for (( j = 0; j < $col; j++ )); do
				echo -en "$(( ${matrixA[$i,$j]} + ${matrixB[$i,$j]} ))"
				if [[ $j -lt $col-1 ]]; then
					echo -en "\t"
				fi
			done
			echo
		done

		return 0
	else
		# Print error to stderr
		echo "Matrices are not the same size!" 1>&2
		exit 2
	fi
}

mean () {
	# If user provided name of matrix file check if it exists, otherwise read from stdin
	if [[ -z $1 ]]; then
		FILE=${1:-/dev/stdin}
	elif [[ -e "$1" ]]; then
		FILE=$1
	elif [[ !(-e "$1") ]]; then
		echo "$1 does not exist!" 1>&2
		exit 1
	fi

	# Use 2D array (dictionary) to perform calculations
	declare -A matrixA

	# Build 2D array
	row=0
	while read line; do
		col=0
		for i in $line; do
			matrixA[$row,$col]=$i
			(( col++ ))
		done
		(( row++ ))
	done < "$FILE"

	# Calculate vector mean, and print to stdout
	for (( i = 0; i < $col; i++ )); do
		sum=0
		for (( j = 0; j < $row; j++ )); do
			sum=$(( sum + ${matrixA[$j,$i]} ))
		done
		echo -en "$(( $sum/$row ))"
		if [[ $i -lt $col-1 ]]; then
			echo -en "\t"
		fi
	done
	echo

	return 0
}

transpose () {
	# If user provided name of matrix file check if it exists, otherwise read from stdin
	if [[ -z $1 ]]; then
		FILE=${1:-/dev/stdin}
	elif [[ -e "$1" ]]; then
		FILE=$1
	elif [[ !(-e "$1") ]]; then
		echo "$1 does not exist!" 1>&2
		exit 1
	fi

	# Use 2D array (dictionary) to perform calculations
	declare -A matrixA

	# Build 2D array
	row=0
	while read line; do
		col=0
		for i in $line; do
			matrixA[$row,$col]=$i
			(( col++ ))
		done
		(( row++ ))
	done < "$FILE"

	# Print array in transposed form to stdout
	for (( i = 0; i < $col; i++ )); do
		for (( j = 0; j < $row; j++ )); do
			echo -en "${matrixA[$j,$i]}"
			if [[ $j -lt $row-1 ]]; then
				echo -en "\t"
			fi
		done
		echo
	done
}

# Switch statement to select function
case $1 in
	"dims")
		if [[ $# -gt 2 ]]; then
			echo "Too many args!" 1>&2
			exit 3
		else
			dims $2
		fi
		;;
	"add")
		if [[ $# -gt 3 ]]; then
			echo "Too many args!" 1>&2
			exit 3
		else
			add $2 $3
		fi
		;;
	"mean")
		if [[ $# -gt 2 ]]; then
			echo "Too many args!" 1>&2
			exit 3
		else
			mean $2
		fi
		;;
	"transpose")
		if [[ $# -gt 2 ]]; then
			echo "Too many args!" 1>&2
			exit 3
		else
			transpose $2
		fi
		;;
	*)
		;;
esac
